#!/usr/local/bin/php -f
<?php
/*
 * ppp-ipv6
 *
 * part of pfSense (https://www.pfsense.org)
 * Copyright (c) 2004-2016 Electric Sheep Fencing, LLC
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgment:
 *    "This product includes software developed by the pfSense Project
 *    for use in the pfSense® software distribution. (http://www.pfsense.org/).
 *
 * 4. The names "pfSense" and "pfSense Project" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    coreteam@pfsense.org.
 *
 * 5. Products derived from this software may not be called "pfSense"
 *    nor may "pfSense" appear in their names without prior written
 *    permission of the Electric Sheep Fencing, LLC.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *
 * "This product includes software developed by the pfSense Project
 * for use in the pfSense software distribution (http://www.pfsense.org/).
 *
 * THIS SOFTWARE IS PROVIDED BY THE pfSense PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE pfSense PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

require_once("globals.inc");
require_once("interfaces.inc");

function interface_ipv6_lower($interface_real) {
	global $g, $config;

	if (!empty($interface_real)) {
		$interface = convert_real_interface_to_friendly_interface_name($interface_real);

		if (!empty($interface) && is_array($config['interfaces'][$interface]) && interface_isppp_type($interface)) {
			$ifcfg = $config['interfaces'][$interface];

            if (!empty($ifcfg['ipaddrv6'])) {
                switch ($ifcfg['ipaddrv6']) {
                    case 'slaac':
                    case 'dhcp6':
                        // Take no action if dhcp6 is active on the parent interface, not the PPP interface
                        if ($ifcfg['ipaddrv6']==='dhcp6' && !(isset($ifcfg['dhcp6usev4iface']) || $ifcfg['ipaddr']==='ppp')) {
                            break;
                        }
                        // bring down dhcp6c if it is running
                        $pidv6 = find_dhcp6c_process($interface_real);
                        if ($pidv6) {
                            posix_kill($pidv6, SIGTERM);
                            sleep(3);
                        }
                        unlink_if_exists("{$g['varetc_path']}/dhcp6c_{$interface}.conf");

                        // disable router advertisements (and therefore SLAAC)
                        mwexec("/sbin/ifconfig " . escapeshellarg($interface_real) . " inet6 -accept_rtadv");

                        // remove any autoconfigured IPv6 addresses
                        exec("/sbin/ifconfig " . escapeshellarg($interface_real) . " inet6", $ifconfig_output);
                        foreach ($ifconfig_output as $output) {
                            if (preg_match('{ \A \s+ inet6 \s+ (\S+) .* autoconf .* \Z}xmsi', $output, $matches)) {
                                mwexec("/sbin/ifconfig " . escapeshellarg($interface_real) . " inet6 " . escapeshellarg($matches[1]) . " delete");
                            }
                        }
                        break;
                    default:
                        break;
                }
            }
		}
	}
}

function interface_ipv6_raise($interface_real) {
	global $config;

	if (!empty($interface_real)) {
		$interface = convert_real_interface_to_friendly_interface_name($interface_real);

		if (!empty($interface) && is_array($config['interfaces'][$interface]) && interface_isppp_type($interface)) {
			$ifcfg = $config['interfaces'][$interface];

            if (!empty($ifcfg['ipaddrv6'])) {
                switch ($ifcfg['ipaddrv6']) {
                    case 'slaac':
                    case 'dhcp6':
                        // Take no action if dhcp6 is active on the parent interface, not the PPP interface
                        if ($ifcfg['ipaddrv6']==='dhcp6' && !(isset($ifcfg['dhcp6usev4iface']) || $ifcfg['ipaddr']==='ppp')) {
                            break;
                        }
                        $pidv6 = find_dhcp6c_process($interface_real);
                        if (empty($pidv6)) {
                            // only fire if router advertisements off
                            // (if router advertisements are on, rtsold might be primed to fire dhcp6c already)
                            exec("/sbin/ifconfig " . escapeshellarg($interface_real) . " inet6", $ifconfig_output);
                            $start = true;
                            foreach ($ifconfig_output as $output) {
                                if (preg_match('{ \A .* ACCEPT_RTADV .* \Z}xmsi', $output)) {
                                    $start = false;
                                    break;
                                }
                            }
                            if ($start) {
                                interface_dhcpv6_configure($interface, $ifcfg);
                            }
                        }
                        break;
                    default:
                        break;
                }
            }
		}
	}
}

// main entry point
if ($argc != 3) {
	goto error;
}

$interface_real = trim($argv[1], " \n\t");
if (empty($interface_real)) {
	goto error;
}

switch (strtolower($argv[2])) {
	case 'up':
		interface_ipv6_raise($interface_real);
		break;
	case 'down':
		interface_ipv6_lower($interface_real);
		break;
	default:
		goto error;
		break;
}

exit(0);

error:
if (!empty($argv[0])) {
	echo("Usage: " . substr(strrchr('/' . $argv[0], '/'), 1) . " <PPP interface> up|down\n");
}
exit(1);

?>
