#!/bin/sh
#
# ppp-linkup
#
# part of pfSense (https://www.pfsense.org)
# Copyright (c) 2004-2013 BSD Perimeter
# Copyright (c) 2013-2016 Electric Sheep Fencing
# Copyright (c) 2014-2022 Rubicon Communications, LLC (Netgate)
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

export PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin

DNSALLOWOVERRIDE=$(/usr/local/sbin/read_xml_tag.sh boolean system/dnsallowoverride)

IF="${1}"
PROTOCOL="${2}"
LOCAL_IP="${3}"
REMOTE_IP="${4}"
AUTH_NAME="${5}"
DNS1_RAW="${6}"
DNS2_RAW="${7}"

if [ "${PROTOCOL}" == "inet" ]; then

	OLD_ROUTER=`cat /tmp/${IF}_router`
	if [ -n "${OLD_ROUTER}" ]; then
		echo "Removing states to old router ${OLD_ROUTER}" | logger -t ppp-linkup
		pfctl -i ${IF} -k 0.0.0.0/0 -k ${OLD_ROUTER}/32
		pfctl -i ${IF} -k ${OLD_ROUTER}/32 -k 0.0.0.0/0
	fi

	# let the configuration system know that the ipv4 has changed.
	echo ${REMOTE_IP} > /tmp/${IF}_router
	/bin/rm -f /tmp/${IF}_router.last
	echo ${LOCAL_IP} > /tmp/${IF}_ip
	touch /tmp/${IF}up
	touch /tmp/${IF}_upstart4

	if [ "${DNSALLOWOVERRIDE}" = "true" ]; then
		# write nameservers to file
		echo -n "" > /var/etc/nameserver_${IF}
		if echo "${DNS1_RAW}" | grep -q dns1; then
			DNS1=`echo "${DNS1_RAW}" | awk '{print $2}'`
			echo "${DNS1}" >> /var/etc/nameserver_${IF}
			route change "${DNS1}" ${REMOTE_IP} \
				|| route add "${DNS1}" ${REMOTE_IP}
		fi
		if echo "${DNS2_RAW}" | grep -q dns2; then
			DNS2=`echo "${DNS2_RAW}" | awk '{print $2}'`
			echo "${DNS2}" >> /var/etc/nameserver_${IF}
			route change "${DNS2}" ${REMOTE_IP} \
				|| route add "${DNS2}" ${REMOTE_IP}
		fi
		pfSctl -c 'service reload dns'
		sleep 1
	fi
	pfSctl -c "interface newip ${IF}"

elif [ "${PROTOCOL}" == "inet6" ]; then
	/usr/local/sbin/ppp-ipv6 ${IF} up
	# let the configuration system know that the ipv6 has changed.
	echo ${REMOTE_IP} |cut -d% -f1 > /tmp/${IF}_routerv6
	/bin/rm -f /tmp/${IF}_routerv6.last
	echo ${LOCAL_IP} |cut -d% -f1 > /tmp/${IF}_ipv6
	touch /tmp/${IF}upv6
	touch /tmp/${IF}_upstart6

	if [ "${DNSALLOWOVERRIDE}" = "true" ]; then
		# write nameservers to file
		echo -n "" > /var/etc/nameserver_v6${IF}
		if echo "${DNS1_RAW}" | grep -q dns1; then
			DNS1=`echo "${DNS1_RAW}" | awk '{print $2}'`
			echo "${DNS1}" >> /var/etc/nameserver_v6${IF}
			route change -inet6 "${DNS1}" ${REMOTE_IP} \
				|| route add -inet6 "${DNS1}" ${REMOTE_IP}
		fi
		if echo "${DNS2_RAW}" | grep -q dns2; then
			DNS2=`echo "${DNS2_RAW}" | awk '{print $2}'`
			echo "${DNS2}" >> /var/etc/nameserver_v6${IF}
			route change -inet6 "${DNS2}" ${REMOTE_IP} \
				|| route add -inet6 "${DNS2}" ${REMOTE_IP}
		fi
		pfSctl -c 'service reload dns'
		sleep 1
	fi
	pfSctl -c "interface newipv6 ${IF}"
fi

exit 0
