#!/bin/sh

touch /var/run/config.lock
/etc/rc.conf_mount_rw

KERNELTYPE=`cat /boot/kernel/pfsense_kernel.txt`
if [ $KERNELTYPE = "wrap" ]; then
	if [ -f /kernels/kernel_wrap.gz ]; then 
		cp /kernels/kernel_wrap.gz /boot/kernel/kernel.gz
		cp /etc/ttys_wrap /etc/ttys
	fi
fi
if [ $KERNELTYPE = "Developers" ]; then
	if [ -f /kernels/kernel_Dev.gz ]; then 
		cp /kernels/kernel_Dev.gz /boot/kernel/kernel.gz
	fi
fi
if [ $KERNELTYPE = "SMP" ]; then
	if [ -f /kernels/kernel_SMP.gz ]; then 
		cp /kernels/kernel_SMP.gz /boot/kernel/kernel.gz
	fi
fi
if [ -d /kernels ]; then
	rm -rf /kernels/*
fi

# Now turn on or off serial console as needed
php -f /tmp/post_upgrade_command.php

# Remove any previous MD5 sum files
rm -f /root/*.md5

# File moved to pfSense php shell (pfSsh.php)
rm -rf /usr/local/sbin/cvs_sync.sh

PFSENSETYPE=`cat /etc/platform`
if [ $PFSENSETYPE = "embedded" ]; then
	cp /etc/ttys_wrap /etc/ttys
fi

if [ -f /usr/local/sbin/php ]; then
	rm /usr/local/sbin/php
fi

