***************
*** 1,10 ****
- # $FreeBSD: src/usr.sbin/pc-sysinstall/backend-query/Makefile,v 1.5 2010/07/13 23:47:12 imp Exp $
  
  FILES=	detect-laptop.sh detect-nics.sh detect-emulation.sh disk-info.sh \
  	disk-list.sh disk-part.sh enable-net.sh get-packages.sh list-config.sh \
  	list-components.sh list-mirrors.sh list-packages.sh list-rsync-backups.sh \
- 	list-tzones.sh query-langs.sh send-logs.sh setup-ssh-keys.sh sys-mem.sh \
- 	test-live.sh test-netup.sh update-part-list.sh xkeyboard-layouts.sh \
  	xkeyboard-models.sh xkeyboard-variants.sh
  FILESMODE=	${BINMODE}
  FILESDIR=${SHAREDIR}/pc-sysinstall/backend-query
--- 1,10 ----
+ # $FreeBSD: src/usr.sbin/pc-sysinstall/backend-query/Makefile,v 1.6 2010/08/19 05:59:27 imp Exp $
  
  FILES=	detect-laptop.sh detect-nics.sh detect-emulation.sh disk-info.sh \
  	disk-list.sh disk-part.sh enable-net.sh get-packages.sh list-config.sh \
  	list-components.sh list-mirrors.sh list-packages.sh list-rsync-backups.sh \
+ 	list-tzones.sh query-langs.sh send-logs.sh set-mirror.sh setup-ssh-keys.sh \
+ 	sys-mem.sh test-live.sh test-netup.sh update-part-list.sh xkeyboard-layouts.sh \
  	xkeyboard-models.sh xkeyboard-variants.sh
  FILESMODE=	${BINMODE}
  FILESDIR=${SHAREDIR}/pc-sysinstall/backend-query
