# $FreeBSD: src/usr.sbin/pc-sysinstall/backend-partmanager/Makefile,v 1.2 2010/06/25 22:35:19 imp Exp $

FILES=	create-part.sh delete-part.sh
FILESMODE=	${BINMODE}
FILESDIR=${SHAREDIR}/pc-sysinstall/backend-partmanager
NO_OBJ=

.include <bsd.prog.mk>
