<?php
/*
 * help.php
 *
 * part of pfSense (https://www.pfsense.org)
 * Copyright (c) 2004-2013 BSD Perimeter
 * Copyright (c) 2013-2016 Electric Sheep Fencing
 * Copyright (c) 2014-2019 Rubicon Communications, LLC (Netgate)
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

require_once("guiconfig.inc");

/* Define hash of jumpto url maps */
$helppages = array(
	'index.php' => 'https://www.netgate.com/docs/pfsense/config/dashboard.html',

	'crash_reporter.php' => 'https://www.netgate.com/docs/pfsense/hardware/unexpected-reboot-troubleshooting.html',
	'diag_arp.php' => 'https://www.netgate.com/docs/pfsense/monitoring/arp-table.html',
	'diag_authentication.php' => 'https://www.netgate.com/docs/pfsense/usermanager/user-authentication-servers.html',
	'diag_backup.php' => 'https://www.netgate.com/docs/pfsense/backup/configuration-backup-and-restore.html',
	'diag_command.php' => 'https://www.netgate.com/docs/pfsense/development/execute-command.html',
	'diag_confbak.php' => 'https://www.netgate.com/docs/pfsense/config/configuration-history.html',
	'diag_defaults.php' => 'https://www.netgate.com/docs/pfsense/config/factory-defaults.html',
	'diag_dns.php' => 'https://www.netgate.com/docs/pfsense/dns/dns-lookup.html',
	'diag_dump_states.php' => 'https://www.netgate.com/docs/pfsense/monitoring/show-states.html',
	'diag_dump_states_sources.php' => 'https://www.netgate.com/docs/pfsense/monitoring/show-source-tracking.html',
	'diag_edit.php' => 'https://www.netgate.com/docs/pfsense/development/edit-file.html',
	'diag_gmirror.php' => 'https://www.netgate.com/docs/pfsense/index.html',
	'diag_halt.php' => 'https://www.netgate.com/docs/pfsense/hardware/halt-system.html',
	'diag_limiter_info.php' => 'https://www.netgate.com/docs/pfsense/trafficshaper/limiters.html',
	'diag_ndp.php' => 'https://www.netgate.com/docs/pfsense/monitoring/ndp-table.html',
	'diag_packet_capture.php' => 'https://www.netgate.com/docs/pfsense/monitoring/performing-a-packet-capture.html',
	'diag_pf_info.php' => 'https://www.netgate.com/docs/pfsense/monitoring/packet-filter-information.html',
	'diag_pftop.php' => 'https://www.netgate.com/docs/pfsense/monitoring/monitoring-bandwidth-usage.html',
	'diag_ping.php' => 'https://www.netgate.com/docs/pfsense/monitoring/ping-host.html',
	'diag_reboot.php' => 'https://www.netgate.com/docs/pfsense/hardware/reboot-system.html',
	'diag_resetstate.php' => 'https://www.netgate.com/docs/pfsense/firewall/reset-states.html',
	'diag_routes.php' => 'https://www.netgate.com/docs/pfsense/routing/viewing-routes.html',
	'diag_smart.php' => 'https://www.netgate.com/docs/pfsense/monitoring/smart-status.html',
	'diag_sockets.php' => 'https://www.netgate.com/docs/pfsense/monitoring/viewing-active-network-sockets.html',
	'diag_states_summary.php' => 'https://www.netgate.com/docs/pfsense/monitoring/states-summary.html',
	'diag_system_activity.php' => 'https://www.netgate.com/docs/pfsense/monitoring/system-activity.html',
	'diag_tables.php' => 'https://www.netgate.com/docs/pfsense/firewall/tables.html',
	'diag_testport.php' => 'https://www.netgate.com/docs/pfsense/monitoring/test-port.html',
	'diag_traceroute.php' => 'https://www.netgate.com/docs/pfsense/monitoring/traceroute.html',
	'easyrule.php' => 'https://www.netgate.com/docs/pfsense/index.html',
	'firewall_aliases_edit.php' => 'https://www.netgate.com/docs/pfsense/firewall/aliases.html',
	'firewall_aliases_import.php' => 'https://www.netgate.com/docs/pfsense/firewall/aliases.html',
	'firewall_aliases.php' => 'https://www.netgate.com/docs/pfsense/firewall/aliases.html',
	'firewall_nat_1to1_edit.php' => 'https://www.netgate.com/docs/pfsense/nat/1-1-nat.html',
	'firewall_nat_1to1.php' => 'https://www.netgate.com/docs/pfsense/nat/1-1-nat.html',
	'firewall_nat_edit.php' => 'https://www.netgate.com/docs/pfsense/nat/forwarding-ports-with-pfsense.html',
	'firewall_nat_npt_edit.php' => 'https://www.netgate.com/docs/pfsense/nat/using-ipv6-network-prefix-translation-npt.html',
	'firewall_nat_npt.php' => 'https://www.netgate.com/docs/pfsense/nat/using-ipv6-network-prefix-translation-npt.html',
	'firewall_nat_out_edit.php' => 'https://www.netgate.com/docs/pfsense/nat/outbound-nat.html',
	'firewall_nat_out.php' => 'https://www.netgate.com/docs/pfsense/nat/outbound-nat.html',
	'firewall_nat.php' => 'https://www.netgate.com/docs/pfsense/nat/forwarding-ports-with-pfsense.html',
	'firewall_rules_edit.php' => 'https://www.netgate.com/docs/pfsense/firewall/firewall-rule-basics.html',
	'firewall_rules.php' => 'https://www.netgate.com/docs/pfsense/firewall/firewall-rule-basics.html',
	'firewall_schedule_edit.php' => 'https://www.netgate.com/docs/pfsense/firewall/firewall-rule-schedules.html',
	'firewall_schedule.php' => 'https://www.netgate.com/docs/pfsense/firewall/firewall-rule-schedules.html',
	'firewall_shaper.php' => 'https://www.netgate.com/docs/pfsense/trafficshaper/traffic-shaping-guide.html',
	'firewall_shaper_queues.php' => 'https://www.netgate.com/docs/pfsense/trafficshaper/traffic-shaping-guide.html',
	'firewall_shaper_vinterface.php' => 'https://www.netgate.com/docs/pfsense/trafficshaper/limiters.html',
	'firewall_shaper_wizards.php' => 'https://www.netgate.com/docs/pfsense/trafficshaper/traffic-shaping-guide.html',
	'firewall_virtual_ip_edit.php' => 'https://www.netgate.com/docs/pfsense/firewall/virtual-ip-address-feature-comparison.html',
	'firewall_virtual_ip.php' => 'https://www.netgate.com/docs/pfsense/firewall/virtual-ip-address-feature-comparison.html',
	'interfaces_assign.php' => 'https://www.netgate.com/docs/pfsense/interfaces/assign-interfaces.html',
	'interfaces_bridge_edit.php' => 'https://www.netgate.com/docs/pfsense/interfaces/interface-bridges.html',
	'interfaces_bridge.php' => 'https://www.netgate.com/docs/pfsense/interfaces/interface-bridges.html',
	'interfaces_gif_edit.php' => 'https://www.netgate.com/docs/pfsense/interfaces/gif-interfaces.html',
	'interfaces_gif.php' => 'https://www.netgate.com/docs/pfsense/interfaces/gif-interfaces.html',
	'interfaces_gre_edit.php' => 'https://www.netgate.com/docs/pfsense/interfaces/gre-interfaces.html',
	'interfaces_gre.php' => 'https://www.netgate.com/docs/pfsense/interfaces/gre-interfaces.html',
	'interfaces_groups_edit.php' => 'https://www.netgate.com/docs/pfsense/interfaces/interface-groups.html',
	'interfaces_groups.php' => 'https://www.netgate.com/docs/pfsense/interfaces/interface-groups.html',
	'interfaces_lagg_edit.php' => 'https://www.netgate.com/docs/pfsense/interfaces/lagg-interfaces.html',
	'interfaces_lagg.php' => 'https://www.netgate.com/docs/pfsense/interfaces/lagg-interfaces.html',
	'interfaces.php' => 'https://www.netgate.com/docs/pfsense/interfaces/interface-settings.html',
	'interfaces_ppps_edit.php' => 'https://www.netgate.com/docs/pfsense/interfaces/ppp-interfaces.html',
	'interfaces_ppps.php' => 'https://www.netgate.com/docs/pfsense/interfaces/ppp-interfaces.html',
	'interfaces_qinq_edit.php' => 'https://www.netgate.com/docs/pfsense/interfaces/qinq-interfaces.html',
	'interfaces_qinq.php' => 'https://www.netgate.com/docs/pfsense/interfaces/qinq-interfaces.html',
	'interfaces_vlan_edit.php' => 'https://www.netgate.com/docs/pfsense/interfaces/vlan-trunking.html',
	'interfaces_vlan.php' => 'https://www.netgate.com/docs/pfsense/interfaces/vlan-trunking.html',
	'interfaces_wireless_edit.php' => 'https://www.netgate.com/docs/pfsense/wireless/wireless-interfaces.html',
	'interfaces_wireless.php' => 'https://www.netgate.com/docs/pfsense/wireless/wireless-interfaces.html',
	'miniupnpd.xml' => 'https://www.netgate.com/docs/pfsense/services/configuring-upnp-and-nat-pmp.html',
	'openvpn-client-export.xml' => 'https://www.netgate.com/docs/pfsense/vpn/openvpn/index.html',
	'pkg_mgr_installed.php' => 'https://www.netgate.com/docs/pfsense/packages/package-manager.html',
	'pkg_mgr_install.php' => 'https://www.netgate.com/docs/pfsense/packages/package-manager.html',
	'pkg_mgr.php' => 'https://www.netgate.com/docs/pfsense/packages/package-manager.html',
	'services_captiveportal_filemanager.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'services_captiveportal_hostname_edit.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'services_captiveportal_hostname.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'services_captiveportal_ip_edit.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'services_captiveportal_ip.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'services_captiveportal_mac_edit.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'services_captiveportal_mac.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'services_captiveportal.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'services_captiveportal_vouchers_edit.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'services_captiveportal_vouchers.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'services_captiveportal_zones_edit.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'services_captiveportal_zones.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'services_checkip_edit.php' => 'https://www.netgate.com/docs/pfsense/dns/ip-address-check-services.html',
	'services_checkip.php' => 'https://www.netgate.com/docs/pfsense/dns/ip-address-check-services.html',
	'services_dhcp_edit.php' => 'https://www.netgate.com/docs/pfsense/dhcp/dhcp-server.html',
	'services_dhcp.php' => 'https://www.netgate.com/docs/pfsense/dhcp/dhcp-server.html',
	'services_dhcp_relay.php' => 'https://www.netgate.com/docs/pfsense/dhcp/dhcp-relay.html',
	'services_dhcpv6_edit.php' => 'https://www.netgate.com/docs/pfsense/dhcp/dhcpv6-server.html',
	'services_dhcpv6.php' => 'https://www.netgate.com/docs/pfsense/dhcp/dhcpv6-server.html',
	'services_dhcpv6_relay.php' => 'https://www.netgate.com/docs/pfsense/dhcp/dhcp-relay.html',
	'services_dnsmasq_domainoverride_edit.php' => 'https://www.netgate.com/docs/pfsense/dns/dns-forwarder.html',
	'services_dnsmasq_edit.php' => 'https://www.netgate.com/docs/pfsense/dns/dns-forwarder.html',
	'services_dnsmasq.php' => 'https://www.netgate.com/docs/pfsense/dns/dns-forwarder.html',
	'services_dyndns_edit.php' => 'https://www.netgate.com/docs/pfsense/dns/dynamic-dns.html',
	'services_dyndns.php' => 'https://www.netgate.com/docs/pfsense/dns/dynamic-dns.html',
	'services_igmpproxy_edit.php' => 'https://www.netgate.com/docs/pfsense/services/igmp-proxy.html',
	'services_igmpproxy.php' => 'https://www.netgate.com/docs/pfsense/services/igmp-proxy.html',
	'services_ntpd_acls.php' => 'https://www.netgate.com/docs/pfsense/services/ntp-server.html',
	'services_ntpd_gps.php' => 'https://www.netgate.com/docs/pfsense/services/ntp-server.html',
	'services_ntpd.php' => 'https://www.netgate.com/docs/pfsense/services/ntp-server.html',
	'services_ntpd_pps.php' => 'https://www.netgate.com/docs/pfsense/services/ntp-server.html',
	'services_pppoe_edit.php' => 'https://www.netgate.com/docs/pfsense/services/pppoe-server-settings.html',
	'services_pppoe.php' => 'https://www.netgate.com/docs/pfsense/services/pppoe-server-settings.html',
	'services_rfc2136_edit.php' => 'https://www.netgate.com/docs/pfsense/dns/dynamic-dns.html',
	'services_rfc2136.php' => 'https://www.netgate.com/docs/pfsense/dns/dynamic-dns.html',
	'services_router_advertisements.php' => 'https://www.netgate.com/docs/pfsense/routing/configuring-ipv6-router-advertisements.html',
	'services_snmp.php' => 'https://www.netgate.com/docs/pfsense/services/snmp-daemon.html',
	'services_unbound_acls.php' => 'https://www.netgate.com/docs/pfsense/dns/unbound-dns-resolver.html',
	'services_unbound_advanced.php' => 'https://www.netgate.com/docs/pfsense/dns/unbound-dns-resolver.html',
	'services_unbound_domainoverride_edit.php' => 'https://www.netgate.com/docs/pfsense/dns/unbound-dns-resolver.html',
	'services_unbound_host_edit.php' => 'https://www.netgate.com/docs/pfsense/dns/unbound-dns-resolver.html',
	'services_unbound.php' => 'https://www.netgate.com/docs/pfsense/dns/unbound-dns-resolver.html',
	'services_wol_edit.php' => 'https://www.netgate.com/docs/pfsense/services/wake-on-lan.html',
	'services_wol.php' => 'https://www.netgate.com/docs/pfsense/services/wake-on-lan.html',
	'status_captiveportal_expire.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'status_captiveportal.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'status_captiveportal_test.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'status_captiveportal_voucher_rolls.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'status_captiveportal_vouchers.php' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'status_carp.php' => 'https://www.netgate.com/docs/pfsense/monitoring/carp-status.html',
	'status_dhcp_leases.php' => 'https://www.netgate.com/docs/pfsense/dhcp/dhcp-leases.html',
	'status_dhcpv6_leases.php' => 'https://www.netgate.com/docs/pfsense/dhcp/dhcpv6-leases.html',
	'status_filter_reload.php' => 'https://www.netgate.com/docs/pfsense/firewall/filter-reload-status.html',
	'status_gateway_groups.php' => 'https://www.netgate.com/docs/pfsense/monitoring/gateway-status.html',
	'status_gateways.php' => 'https://www.netgate.com/docs/pfsense/monitoring/gateway-status.html',
	'status_graph_cpu.php' => 'https://www.netgate.com/docs/pfsense/index.html',
	'status_graph.php' => 'https://www.netgate.com/docs/pfsense/monitoring/traffic-graph.html',
	'status_interfaces.php' => 'https://www.netgate.com/docs/pfsense/monitoring/interface-status.html',
	'status_ipsec_leases.php' => 'https://www.netgate.com/docs/pfsense/vpn/ipsec/ipsec-mobile-clients.html',
	'status_ipsec.php' => 'https://www.netgate.com/docs/pfsense/vpn/ipsec/ipsec-status.html',
	'status_ipsec_sad.php' => 'https://www.netgate.com/docs/pfsense/vpn/ipsec/ipsec-status.html',
	'status_ipsec_spd.php' => 'https://www.netgate.com/docs/pfsense/vpn/ipsec/ipsec-status.html',
	'status_logs_filter_dynamic.php' => 'https://www.netgate.com/docs/pfsense/monitoring/firewall-logs.html',
	'status_logs_filter.php' => 'https://www.netgate.com/docs/pfsense/monitoring/firewall-logs.html',
	'status_logs_filter_summary.php' => 'https://www.netgate.com/docs/pfsense/monitoring/firewall-logs.html',
	'status_logs.php-dhcpd' => 'https://www.netgate.com/docs/pfsense/dhcp/dhcp-logs.html',
	'status_logs.php-gateways' => 'https://www.netgate.com/docs/pfsense/monitoring/gateway-logs.html',
	'status_logs.php' => 'https://www.netgate.com/docs/pfsense/monitoring/system-logs.html',
	'status_logs.php-ipsec' => 'https://www.netgate.com/docs/pfsense/vpn/ipsec/ipsec-logs.html',
	'status_logs.php-ntpd' => 'https://www.netgate.com/docs/pfsense/monitoring/ntp-logs.html',
	'status_logs.php-openvpn' => 'https://www.netgate.com/docs/pfsense/vpn/openvpn/index.html',
	'status_logs.php-portalauth' => 'https://www.netgate.com/docs/pfsense/captiveportal/captive-portal.html',
	'status_logs.php-ppp' => 'https://www.netgate.com/docs/pfsense/monitoring/ppp-logs.html',
	'status_logs.php-resolver' => 'https://www.netgate.com/docs/pfsense/monitoring/resolver-logs.html',
	'status_logs.php-routing' => 'https://www.netgate.com/docs/pfsense/monitoring/routing-logs.html',
	'status_logs.php-wireless' => 'https://www.netgate.com/docs/pfsense/wireless/wireless-logs.html',
	'status_logs_packages.php' => 'https://docs.netgate.com/pfsense/en/latest/monitoring/package-logs.html',
	'status_logs_settings.php' => 'https://www.netgate.com/docs/pfsense/monitoring/log-settings.html',
	'status_logs_vpn.php' => 'https://www.netgate.com/docs/pfsense/index.html',
	'status_ntpd.php' => 'https://www.netgate.com/docs/pfsense/services/ntp-server.html',
	'status_openvpn.php' => 'https://www.netgate.com/docs/pfsense/vpn/openvpn/index.html',
	'status_queues.php' => 'https://www.netgate.com/docs/pfsense/trafficshaper/traffic-shaping-guide.html',
	'status_services.php' => 'https://www.netgate.com/docs/pfsense/monitoring/services-status.html',
	'status_upnp.php' => 'https://www.netgate.com/docs/pfsense/services/configuring-upnp-and-nat-pmp.html',
	'status_wireless.php' => 'https://www.netgate.com/docs/pfsense/wireless/wireless-status.html',
	'system_advanced_admin.php' => 'https://www.netgate.com/docs/pfsense/config/advanced-setup.html',
	'system_advanced_firewall.php' => 'https://www.netgate.com/docs/pfsense/config/advanced-setup.html',
	'system_advanced_misc.php' => 'https://www.netgate.com/docs/pfsense/config/advanced-setup.html',
	'system_advanced_network.php' => 'https://www.netgate.com/docs/pfsense/config/advanced-setup.html',
	'system_advanced_notifications.php' => 'https://www.netgate.com/docs/pfsense/config/advanced-setup.html',
	'system_advanced_sysctl.php' => 'https://www.netgate.com/docs/pfsense/config/advanced-setup.html',
	'system_authservers.php' => 'https://www.netgate.com/docs/pfsense/usermanager/user-authentication-servers.html',
	'system_camanager.php' => 'https://www.netgate.com/docs/pfsense/certificates/certificate-management.html',
	'system_certmanager.php' => 'https://www.netgate.com/docs/pfsense/certificates/certificate-management.html',
	'system_crlmanager.php' => 'https://www.netgate.com/docs/pfsense/certificates/certificate-management.html',
	'system_gateway_groups_edit.php' => 'https://www.netgate.com/docs/pfsense/routing/gateway-settings.html',
	'system_gateway_groups.php' => 'https://www.netgate.com/docs/pfsense/routing/gateway-settings.html',
	'system_gateways_edit.php' => 'https://www.netgate.com/docs/pfsense/routing/gateway-settings.html',
	'system_gateways.php' => 'https://www.netgate.com/docs/pfsense/routing/gateway-settings.html',
	'system_groupmanager_addprivs.php' => 'https://www.netgate.com/docs/pfsense/usermanager/group-manager.html',
	'system_groupmanager.php' => 'https://www.netgate.com/docs/pfsense/usermanager/group-manager.html',
	'system_hasync.php' => 'https://www.netgate.com/docs/pfsense/highavailability/index.html',
	'system.php' => 'https://www.netgate.com/docs/pfsense/config/general-setup.html',
	'system_routes_edit.php' => 'https://www.netgate.com/docs/pfsense/routing/static-routes.html',
	'system_routes.php' => 'https://www.netgate.com/docs/pfsense/routing/static-routes.html',
	'system_update_settings.php' => 'https://www.netgate.com/docs/pfsense/install/upgrading-pfsense-software-installations.html',
	'system_usermanager_addprivs.php' => 'https://www.netgate.com/docs/pfsense/usermanager/managing-local-users.html',
	'system_usermanager_passwordmg.php' => 'https://www.netgate.com/docs/pfsense/usermanager/managing-local-users.html',
	'system_usermanager.php' => 'https://www.netgate.com/docs/pfsense/usermanager/managing-local-users.html',
	'system_usermanager_settings.php' => 'https://www.netgate.com/docs/pfsense/usermanager/managing-local-users.html',
	'system_user_settings.php' => 'https://www.netgate.com/docs/pfsense/usermanager/managing-local-users.html',
	'vpn_ipsec_keys_edit.php' => 'https://www.netgate.com/docs/pfsense/vpn/ipsec/ipsec-tunnels.html',
	'vpn_ipsec_keys.php' => 'https://www.netgate.com/docs/pfsense/vpn/ipsec/ipsec-tunnels.html',
	'vpn_ipsec_mobile.php' => 'https://www.netgate.com/docs/pfsense/vpn/ipsec/ipsec-mobile-clients.html',
	'vpn_ipsec_phase1.php' => 'https://www.netgate.com/docs/pfsense/vpn/ipsec/ipsec-tunnels.html',
	'vpn_ipsec_phase2.php' => 'https://www.netgate.com/docs/pfsense/vpn/ipsec/ipsec-tunnels.html',
	'vpn_ipsec.php' => 'https://www.netgate.com/docs/pfsense/vpn/ipsec/ipsec-tunnels.html',
	'vpn_ipsec_settings.php' => 'https://www.netgate.com/docs/pfsense/vpn/ipsec/advanced-ipsec-settings.html',
	'vpn_l2tp.php' => 'https://www.netgate.com/docs/pfsense/vpn/l2tp-vpn-settings.html',
	'vpn_l2tp_users_edit.php' => 'https://www.netgate.com/docs/pfsense/vpn/l2tp-vpn-settings.html',
	'vpn_l2tp_users.php' => 'https://www.netgate.com/docs/pfsense/vpn/l2tp-vpn-settings.html',
	'vpn_openvpn_client.php' => 'https://www.netgate.com/docs/pfsense/vpn/openvpn/index.html',
	'vpn_openvpn_csc.php' => 'https://www.netgate.com/docs/pfsense/vpn/openvpn/index.html',
	'vpn_openvpn_export.php' => 'https://www.netgate.com/docs/pfsense/vpn/openvpn/index.html',
	'vpn_openvpn_export_shared.php' => 'https://www.netgate.com/docs/pfsense/vpn/openvpn/index.html',
	'vpn_openvpn_server.php' => 'https://www.netgate.com/docs/pfsense/vpn/openvpn/index.html',

	/* Packages from here on down. Not checked as strictly. Pages may not yet exist. */
	'acme/acme_accountkeys_edit.php' => 'https://www.netgate.com/docs/pfsense/certificates/acme-package.html',
	'acme/acme_accountkeys.php' => 'https://www.netgate.com/docs/pfsense/certificates/acme-package.html',
	'acme/acme_certificates_edit.php' => 'https://www.netgate.com/docs/pfsense/certificates/acme-package.html',
	'acme/acme_certificates.php' => 'https://www.netgate.com/docs/pfsense/certificates/acme-package.html',
	'acme/acme_generalsettings.php' => 'https://www.netgate.com/docs/pfsense/certificates/acme-package.html',
	'acme.xml' => 'https://www.netgate.com/docs/pfsense/certificates/acme-package.html',
	'apcupsd_status.php' => 'https://www.netgate.com/docs/pfsense/index.php/Apcupsd_package',
	'apcupsd.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Apcupsd_package',
	'arping.xml' => 'https://www.netgate.com/docs/pfsense/packages/arping-package.html',
	'autoconfigbackup_backup.php' => 'https://www.netgate.com/docs/pfsense/backup/autoconfigbackup.html',
	'autoconfigbackup.php' => 'https://www.netgate.com/docs/pfsense/backup/autoconfigbackup.html',
	'autoconfigbackup_stats.php' => 'https://www.netgate.com/docs/pfsense/backup/autoconfigbackup.html',
	'autoconfigbackup.xml' => 'https://www.netgate.com/docs/pfsense/backup/autoconfigbackup.html',
	'avahi.xml' => 'https://www.netgate.com/docs/pfsense/packages/avahi-package.html',
	'backup.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Backup_package',
	'bind_acls.xml' => 'https://www.netgate.com/docs/pfsense/index.php/BIND_package',
	'bind_sync.xml' => 'https://www.netgate.com/docs/pfsense/index.php/BIND_package',
	'bind_views.xml' => 'https://www.netgate.com/docs/pfsense/index.php/BIND_package',
	'bind.xml' => 'https://www.netgate.com/docs/pfsense/index.php/BIND_package',
	'bind_zones.xml' => 'https://www.netgate.com/docs/pfsense/index.php/BIND_package',
	'blinkled.xml' => 'https://www.netgate.com/docs/pfsense/index.html',
	'cellular.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Cellular_package',
	'cron.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Cron_package',
	'darkstat.xml' => 'https://www.netgate.com/docs/pfsense/monitoring/monitoring-bandwidth-usage.html',
	'freeradiusauthorizedmacs.xml' => 'https://www.netgate.com/docs/pfsense/usermanager/plain-mac-authentication-with-freeradius.rst',
	'freeradiuscerts.xml' => 'https://www.netgate.com/docs/pfsense/usermanager/freeradius-2-x-package.html',
	'freeradiusclients.xml' => 'https://www.netgate.com/docs/pfsense/usermanager/freeradius-2-x-package.html',
	'freeradiuseapconf.xml' => 'https://www.netgate.com/docs/pfsense/usermanager/using-eap-and-peap-with-freeradius.html',
	'freeradiusinterfaces.xml' => 'https://www.netgate.com/docs/pfsense/usermanager/freeradius-2-x-package.html',
	'freeradiusmodulesldap.xml' => 'https://www.netgate.com/docs/pfsense/usermanager/freeradius-2-x-package.html',
	'freeradiussettings.xml' => 'https://www.netgate.com/docs/pfsense/usermanager/freeradius-2-x-package.html',
	'freeradiussqlconf.xml' => 'https://www.netgate.com/docs/pfsense/usermanager/using-mysql-with-freeradius.html',
	'freeradiussync.xml' => 'https://www.netgate.com/docs/pfsense/usermanager/freeradius-2-x-package.html',
	'freeradius_view_config.php' => 'https://www.netgate.com/docs/pfsense/usermanager/freeradius-2-x-package.html',
	'freeradius.xml' => 'https://www.netgate.com/docs/pfsense/usermanager/freeradius-2-x-package.html',
	'ftpproxy.xml' => 'https://www.netgate.com/docs/pfsense/index.php/FTP_Proxy_package',
	'gwled.php' => 'https://www.netgate.com/docs/pfsense/index.php/Gwled_package',
	'gwled.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Gwled_package',
	'haproxy/haproxy_files.php' => 'https://www.netgate.com/docs/pfsense/packages/haproxy-package.html',
	'haproxy/haproxy_global.php' => 'https://www.netgate.com/docs/pfsense/packages/haproxy-package.html',
	'haproxy/haproxy_listeners_edit.php' => 'https://www.netgate.com/docs/pfsense/packages/haproxy-package.html',
	'haproxy/haproxy_listeners.php' => 'https://www.netgate.com/docs/pfsense/packages/haproxy-package.html',
	'haproxy/haproxy_pool_edit.php' => 'https://www.netgate.com/docs/pfsense/packages/haproxy-package.html',
	'haproxy/haproxy_pools.php' => 'https://www.netgate.com/docs/pfsense/packages/haproxy-package.html',
	'haproxy/haproxy_stats.php' => 'https://www.netgate.com/docs/pfsense/packages/haproxy-package.html',
	'haproxy/haproxy_templates.php' => 'https://www.netgate.com/docs/pfsense/packages/haproxy-package.html',
	'haproxy.xml' => 'https://www.netgate.com/docs/pfsense/packages/haproxy-package.html',
	'iftop.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Iftop_package',
	'iperfserver.xml' => 'https://www.netgate.com/docs/pfsense/packages/iperf-package.html',
	'iperf.xml' => 'https://www.netgate.com/docs/pfsense/packages/iperf-package.html',
	'ladvd.xml' => 'https://www.netgate.com/docs/pfsense/index.php/LADVD_package',
	'lcdproc.xml' => 'https://www.netgate.com/docs/pfsense/index.php/LCDProc_package',
	'lightsquid.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Lightsquid_package',
	'mailreport.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Mail_Reports_package',
	'mtr-nox11.xml' => 'https://www.netgate.com/docs/pfsense/index.php/MTR_package',
	'net-snmp_communities.xml' => 'https://www.netgate.com/docs/pfsense/index.php/NET-SNMP_package',
	'net-snmptrapd_communities.xml' => 'https://www.netgate.com/docs/pfsense/index.php/NET-SNMP_package',
	'net-snmptrapd_formats.xml' => 'https://www.netgate.com/docs/pfsense/index.php/NET-SNMP_package',
	'net-snmptrapd_forwards.xml' => 'https://www.netgate.com/docs/pfsense/index.php/NET-SNMP_package',
	'net-snmptrapd_traphandles.xml' => 'https://www.netgate.com/docs/pfsense/index.php/NET-SNMP_package',
	'net-snmptrapd_users.xml' => 'https://www.netgate.com/docs/pfsense/index.php/NET-SNMP_package',
	'net-snmptrapd.xml' => 'https://www.netgate.com/docs/pfsense/index.php/NET-SNMP_package',
	'net-snmp_trapgen.xml' => 'https://www.netgate.com/docs/pfsense/index.php/NET-SNMP_package',
	'net-snmp_users.xml' => 'https://www.netgate.com/docs/pfsense/index.php/NET-SNMP_package',
	'net-snmp.xml' => 'https://www.netgate.com/docs/pfsense/index.php/NET-SNMP_package',
	'nmap.xml' => 'https://www.netgate.com/docs/pfsense/packages/nmap-package.html',
	'notes.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Notes_package',
	'nrpe.xml' => 'https://www.netgate.com/docs/pfsense/index.php/NRPE_package',
	'ntopng.xml' => 'https://www.netgate.com/docs/pfsense/monitoring/monitoring-bandwidth-usage.html',
	'nut_settings.php' => 'https://www.netgate.com/docs/pfsense/packages/nut-package.html',
	'nut_status.php' => 'https://www.netgate.com/docs/pfsense/packages/nut-package.html',
	'nut.xml' => 'https://www.netgate.com/docs/pfsense/packages/nut-package.html',
	'openbgpd_groups.xml' => 'https://www.netgate.com/docs/pfsense/packages/openbgpd-package.html',
	'openbgpd_neighbors.xml' => 'https://www.netgate.com/docs/pfsense/packages/openbgpd-package.html',
	'openbgpd_raw.php' => 'https://www.netgate.com/docs/pfsense/packages/openbgpd-package.html',
	'openbgpd_status.php' => 'https://www.netgate.com/docs/pfsense/packages/openbgpd-package.html',
	'openbgpd.xml' => 'https://www.netgate.com/docs/pfsense/packages/openbgpd-package.html',
	'open-vm-tools.xml' => 'https://www.netgate.com/docs/pfsense/packages/open-vm-tools-package.html',
	'packages/backup/backup_edit.php' => 'https://www.netgate.com/docs/pfsense/index.php/Backup_package',
	'packages/backup/backup.php' => 'https://www.netgate.com/docs/pfsense/index.php/Backup_package',
	'packages/cron/cron_edit.php' => 'https://www.netgate.com/docs/pfsense/index.php/Cron_package',
	'packages/cron/cron.php' => 'https://www.netgate.com/docs/pfsense/index.php/Cron_package',
	'packages/cron/index.php' => 'https://www.netgate.com/docs/pfsense/index.php/Cron_package',
	'packages/lcdproc/index.php' => 'https://www.netgate.com/docs/pfsense/index.php/LCDProc_package',
	'packages/lcdproc/lcdproc.php' => 'https://www.netgate.com/docs/pfsense/index.php/LCDProc_package',
	'packages/lcdproc/lcdproc_screens.php' => 'https://www.netgate.com/docs/pfsense/index.php/LCDProc_package',
	'pfblockerng/pfblockerng_alerts_ar.php' => 'https://www.netgate.com/docs/pfsense/packages/pfblocker.html',
	'pfblockerng/pfblockerng_alerts.php' => 'https://www.netgate.com/docs/pfsense/packages/pfblocker.html',
	'pfblockerng/pfblockerng_dnsbl_easylist.xml' => 'https://www.netgate.com/docs/pfsense/packages/pfblocker.html',
	'pfblockerng/pfblockerng_dnsbl_lists.xml' => 'https://www.netgate.com/docs/pfsense/packages/pfblocker.html',
	'pfblockerng/pfblockerng_dnsbl.xml' => 'https://www.netgate.com/docs/pfsense/packages/pfblocker.html',
	'pfblockerng/pfblockerng_log.php' => 'https://www.netgate.com/docs/pfsense/packages/pfblocker.html',
	'pfblockerng/pfblockerng.php' => 'https://www.netgate.com/docs/pfsense/packages/pfblocker.html',
	'pfblockerng/pfblockerng_sync.xml' => 'https://www.netgate.com/docs/pfsense/packages/pfblocker.html',
	'pfblockerng/pfblockerng_threats.php' => 'https://www.netgate.com/docs/pfsense/packages/pfblocker.html',
	'pfblockerng/pfblockerng_update.php' => 'https://www.netgate.com/docs/pfsense/packages/pfblocker.html',
	'pfblockerng/pfblockerng_v4lists.xml' => 'https://www.netgate.com/docs/pfsense/packages/pfblocker.html',
	'pfblockerng/pfblockerng_v6lists.xml' => 'https://www.netgate.com/docs/pfsense/packages/pfblocker.html',
	'pfblockerng/www/index.php' => 'https://www.netgate.com/docs/pfsense/packages/pfblocker.html',
	'pfblockerng.xml' => 'https://www.netgate.com/docs/pfsense/packages/pfblocker.html',
	'quagga_ospfd_interfaces.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Quagga_package',
	'quagga_ospfd_raw.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Quagga_package',
	'quagga_ospfd.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Quagga_package',
	'routed.xml' => 'https://www.netgate.com/docs/pfsense/packages/routing-information-protocol-rip.html',
	'services_servicewatchdog_add.php' => 'https://www.netgate.com/docs/pfsense/index.php/Service_Watchdog_package',
	'services_servicewatchdog.php' => 'https://www.netgate.com/docs/pfsense/index.php/Service_Watchdog_package',
	'servicewatchdog.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Service_Watchdog_package',
	'shellcmd.xml' => 'https://www.netgate.com/docs/pfsense/development/executing-commands-at-boot-time.html',
	'siproxd_registered_phones.php' => 'https://www.netgate.com/docs/pfsense/packages/siproxd-package.html',
	'siproxdusers.xml' => 'https://www.netgate.com/docs/pfsense/packages/siproxd-package.html',
	'siproxd.xml' => 'https://www.netgate.com/docs/pfsense/packages/siproxd-package.html',
	'snort/snort_alerts.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-alerts.html',
	'snort/snort_barnyard.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-barnyard2.html',
	'snort/snort_blocked.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-blocked-hosts.html',
	'snort/snort_define_servers.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-define-servers.html',
	'snort/snort_download_rules.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-updates.html',
	'snort/snort_download_updates.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-updates.html',
	'snort/snort_edit_hat_data.php' => 'https://www.netgate.com/docs/pfsense/index.php/Category:Snort',
	'snort/snort_frag3_engine.php' => 'https://www.netgate.com/docs/pfsense/index.php/Category:Snort',
	'snort/snort_ftp_client_engine.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-preprocessors.html',
	'snort/snort_ftp_server_engine.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-preprocessors.html',
	'snort/snort_httpinspect_engine.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-preprocessors.html',
	'snort/snort_import_aliases.php' => 'https://www.netgate.com/docs/pfsense/index.php/Category:Snort',
	'snort/snort_interface_logs.php' => 'https://www.netgate.com/docs/pfsense/index.php/Category:Snort',
	'snort/snort_interfaces_edit.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-interfaces.html',
	'snort/snort_interfaces_global.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-interfaces.html',
	'snort/snort_interfaces.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-interfaces.html',
	'snort/snort_interfaces_suppress_edit.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-suppress-list.html',
	'snort/snort_interfaces_suppress.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-suppress-list.html',
	'snort/snort_ip_list_mgmt.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-ip-list-mgmt.html',
	'snort/snort_iprep_list_browser.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-ip-reputation.html',
	'snort/snort_ip_reputation.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-ip-reputation.html',
	'snort/snort_list_view.php' => 'https://www.netgate.com/docs/pfsense/index.php/Category:Snort',
	'snort/snort_log_mgmt.php' => 'https://www.netgate.com/docs/pfsense/index.php/Category:Snort',
	'snort/snort_passlist_edit.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-passlist.html',
	'snort/snort_passlist.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-passlist.html',
	'snort/snort_preprocessors.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-preprocessors.html',
	'snort/snort_rules_edit.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-rules.html',
	'snort/snort_rulesets.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-rules.html',
	'snort/snort_rules_flowbits.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-rules.html',
	'snort/snort_rules.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-rules.html',
	'snort/snort_select_alias.php' => 'https://www.netgate.com/docs/pfsense/index.php/Category:Snort',
	'snort/snort_sid_mgmt.php' => 'https://www.netgate.com/docs/pfsense/index.php/Category:Snort',
	'snort/snort_stream5_engine.php' => 'https://www.netgate.com/docs/pfsense/index.php/Category:Snort',
	'snort/snort_sync.xml' => 'https://www.netgate.com/docs/pfsense/ids-ips/snort-xmlrpc-synchronization.html',
	'snort.xml' => 'https://www.netgate.com/docs/pfsense/ids-ips/setup-snort-package.html',
	'softflowd.xml' => 'https://www.netgate.com/docs/pfsense/monitoring/exporting-netflow-with-softflowd.html',
	'sqstat/sqstat.class.php' => 'https://www.netgate.com/docs/pfsense/index.php/Sqstat_package',
	'sqstat/sqstat.php' => 'https://www.netgate.com/docs/pfsense/index.php/Sqstat_package',
	'squid_antivirus.xml' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'squid_auth.xml' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'squid_cache.xml' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'squidguard_acl.xml' => 'https://www.netgate.com/docs/pfsense/cache-proxy/squidguard-package.html',
	'squidguard_default.xml' => 'https://www.netgate.com/docs/pfsense/cache-proxy/squidguard-package.html',
	'squidguard_dest.xml' => 'https://www.netgate.com/docs/pfsense/cache-proxy/squidguard-package.html',
	'squidguard_rewr.xml' => 'https://www.netgate.com/docs/pfsense/cache-proxy/squidguard-package.html',
	'squidGuard/squidguard_blacklist.php' => 'https://www.netgate.com/docs/pfsense/cache-proxy/squidguard-package.html',
	'squidGuard/squidguard_log.php' => 'https://www.netgate.com/docs/pfsense/cache-proxy/squidguard-package.html',
	'squidguard_sync.xml' => 'https://www.netgate.com/docs/pfsense/cache-proxy/squidguard-package.html',
	'squidguard_time.xml' => 'https://www.netgate.com/docs/pfsense/cache-proxy/squidguard-package.html',
	'squidguard.xml' => 'https://www.netgate.com/docs/pfsense/cache-proxy/squidguard-package.html',
	'squid_log_parser.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'squid_monitor_data.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'squid_monitor.php' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'squid_reverse_general.xml' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'squid_reverse_peer.xml' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'squid_reverse_redir.xml' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'squid_reverse_sync.xml' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'squid_reverse_uri.xml' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'squid_sync.xml' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'squid_traffic.xml' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'squid_upstream.xml' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'squid_users.xml' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'squid.xml' => 'https://www.netgate.com/docs/pfsense/ids-ips/index.html',
	'status_ladvd.php' => 'https://www.netgate.com/docs/pfsense/index.php/LADVD_package',
	'status_mail_report_add_cmd.php' => 'https://www.netgate.com/docs/pfsense/index.php/Mail_Reports_package',
	'status_mail_report_add_log.php' => 'https://www.netgate.com/docs/pfsense/index.php/Mail_Reports_package',
	'status_mail_report_edit.php' => 'https://www.netgate.com/docs/pfsense/index.php/Mail_Reports_package',
	'status_mail_report.php' => 'https://www.netgate.com/docs/pfsense/index.php/Mail_Reports_package',
	'status_ospfd.php' => 'https://www.netgate.com/docs/pfsense/index.php/Quagga_package',
	'status_tinc.php' => 'https://www.netgate.com/docs/pfsense/index.php/Tinc_package',
	'status_traffic_totals.php' => 'https://www.netgate.com/docs/pfsense/index.php/Traffic_Totals_package',
	'stunnel_certs.xml' => 'https://www.netgate.com/docs/pfsense/packages/stunnel-package.html',
	'stunnel.xml' => 'https://www.netgate.com/docs/pfsense/packages/stunnel-package.html',
	'sudo.xml' => 'https://www.netgate.com/docs/pfsense/usermanager/sudo-package.html',
	'suricata/suricata_alerts.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_app_parsers.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_barnyard.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_blocked.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_define_vars.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_download_rules.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_download_updates.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_flow_stream.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_global.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_import_aliases.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_interfaces_edit.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_interfaces.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_ip_list_mgmt.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_iprep_list_browser.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_ip_reputation.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_libhtp_policy_engine.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_list_view.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_logs_browser.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_logs_mgmt.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_os_policy_engine.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_passlist_edit.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_passlist.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_rules_edit.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_rulesets.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_rules_flowbits.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_rules.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_select_alias.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_sid_mgmt.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_suppress_edit.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_suppress.php' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata/suricata_sync.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'suricata.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Suricata_package',
	'syslog-ng_advanced.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Syslog-ng_package',
	'syslog-ng_log_viewer.php' => 'https://www.netgate.com/docs/pfsense/index.php/Syslog-ng_package',
	'syslog-ng.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Syslog-ng_package',
	'system_patches_edit.php' => 'https://www.netgate.com/docs/pfsense/development/system-patches.html',
	'system_patches.php' => 'https://www.netgate.com/docs/pfsense/development/system-patches.html',
	'systempatches.xml' => 'https://www.netgate.com/docs/pfsense/development/system-patches.html',
	'tftpd.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Tftpd_package',
	'tftp_files.php' => 'https://www.netgate.com/docs/pfsense/index.php/Tftpd_package',
	'tinc_hosts.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Tinc_package',
	'tinc.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Tinc_package',
	'vpc_vpn_wizard.xml' => 'https://docs.netgate.com/pfsense/en/latest/solutions/aws-vpn-appliance/vpc-wizard-guide.html',
	'zabbix-agent-lts.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Zabbix_Agent_package',
	'zabbix-proxy-lts.xml' => 'https://www.netgate.com/docs/pfsense/index.php/Zabbix_Proxy_package',
);

$pagename = "";
/* Check for parameter "page". */
if ($_REQUEST && isset($_REQUEST['page'])) {
	$pagename = $_REQUEST['page'];
}

/* If "page" is not found, check referring URL */
if (empty($pagename)) {
	/* Attempt to parse out filename */
	$uri_split = "";
	preg_match("/\/(.*)\?(.*)/", $_SERVER["HTTP_REFERER"], $uri_split);

	/* If there was no match, there were no parameters, just grab the filename
		Otherwise, use the matched filename from above. */
	if (empty($uri_split[0])) {
		$pagename = ltrim(parse_url($_SERVER["HTTP_REFERER"], PHP_URL_PATH), '/');
	} else {
		$pagename = $uri_split[1];
	}

	/* If the referrer was index.php then this was a redirect to help.php
	   because help.php was the first page the user has priv to.
	   In that case we do not want to redirect off to the dashboard help. */
	if ($pagename == "index.php") {
		$pagename = "";
	}

	/* If the filename is pkg_edit.php or wizard.php, reparse looking
		for the .xml filename */
	if (($pagename == "pkg.php") || ($pagename == "pkg_edit.php") || ($pagename == "wizard.php")) {
		$param_split = explode('&', $uri_split[2]);
		foreach ($param_split as $param) {
			if (substr($param, 0, 4) == "xml=") {
				$xmlfile = explode('=', $param);
				$pagename = $xmlfile[1];
			}
		}
	}
}

/* Using the derived page name, attempt to find in the URL mapping hash */
if (strlen($pagename) > 0) {
	if (array_key_exists($pagename, $helppages)) {
		$helppage = $helppages[$pagename];
	} else {
		// If no specific page was found, use a generic help page
		$helppage = 'https://doc.pfsense.org/index.php/No_Help_Found';
	}

	/* Redirect to help page. */
	header("Location: {$helppage}");
}

// No page name was determined, so show a message.
$pgtitle = array(gettext("Help"), gettext("About this Page"));
require_once("head.inc");

if (is_array($allowedpages) && str_replace('*', '', $allowedpages[0]) == "help.php") {
	if (count($allowedpages) == 1) {
		print_info_box(gettext("The Help page is the only page this user has privilege for."));
	} else {
		print_info_box(gettext("Displaying the Help page because it is the first page this user has privilege for."));
	}
} else {
	print_info_box(gettext("Help page accessed directly without any page parameter."));
}

include("foot.inc");
?>
