#!/bin/sh
/sbin/pfctl -i $1 -Fs
# delete the node just in case mpd cannot do that
/bin/rm -f /var/etc/nameserver_$1
/bin/rm -f /tmp/$1_router
/bin/rm -f /tmp/$1up
/usr/local/sbin/pfSctl -c 'filter reload'
