#!/bin/sh

# let the configuration system know that the ip has changed.
#/usr/local/sbin/pfSctl -c "interface newip $interface"

if [ "${dev_type}" = "tun" ]; then
	if [ -n "${route_vpn_gateway}" ]; then
		/bin/echo ${route_vpn_gateway} > /tmp/${1}_router
	elif [ -n "${ifconfig_remote}" ]; then
		/bin/echo ${ifconfig_remote} > /tmp/${1}_router
	elif [ -n "${ifconfig_local}" ]; then
		/bin/echo ${ifconfig_local} > /tmp/${1}_router
	else
		/bin/echo ${5} > /tmp/${1}_router
	fi
fi

/usr/bin/touch /tmp/${1}up
# reload filter
/usr/local/sbin/pfSctl -c "interface newip ${1}"
exit 0
