#!/bin/sh

# write nameservers to file needs dns fidnings?!

# let the configuration system know that the ip has changed.
#/usr/local/sbin/pfSctl -c "interface newip $interface"
/bin/echo $4 > /tmp/$1_router
/usr/bin/touch /tmp/$1up
# reload filter 
/usr/local/sbin/pfSctl -c 'filter reload'
exit 0
