#!/bin/sh

# let the configuration system know that the ip has changed.
/bin/echo $4 > /tmp/$1_router
/bin/echo $3 > /tmp/$1_ip
/usr/bin/touch /tmp/$1up

ALLOWOVERRIDE=`/usr/bin/grep -c dnsallowoverride /conf/config.xml`
if [ $ALLOWOVERRIDE -gt 0 ]; then
	# write nameservers to file
	if [ "`echo $6|grep -c dns1`" -gt 0 ]; then
		DNS1=`echo $6 |awk '{print $2}'`
		echo "$DNS1"> /var/etc/nameserver_$1
		/sbin/route delete ${DNS1}
		/sbin/route add ${DNS1} $4
	fi
	if [ "`echo $7|grep -c dns2`" -gt 0 ]; then
		DNS2=`echo $7 |awk '{print $2}'`
		echo "$DNS2" >> /var/etc/nameserver_$1
		/sbin/route delete ${DNS2}
		/sbin/route add ${DNS2} $4
	fi
	/usr/local/sbin/pfSctl -c 'service reload dns'
	/bin/sleep 1
fi

/usr/local/sbin/pfSctl -c "interface newip $1"
exit 0
