#!/bin/sh
if [ -f /tmp/$1up ] && [ -f /conf/$1.log ]; then
        seconds=$((`date -j +%s` - `/usr/bin/stat -f %m /tmp/$1up`))
        /usr/local/sbin/ppp-log-uptime.sh $seconds $1 &
fi
if [ -f "/tmp/${interface}_defaultgw" ]; then
	route delete default $4
fi
/sbin/pfctl -k 0.0.0.0/0 -k $3
/sbin/pfctl -k $3
pfctl -K $3
/sbin/pfctl -b 0.0.0.0/32 -b $4
# delete the node just in case mpd cannot do that
/usr/sbin/ngctl shutdown $1:
if [ -f "/var/etc/nameserver_$1" ]; then
	# Remove old entries
	for nameserver in `cat /var/etc/nameserver_$1`; do
		/sbin/route delete $nameserver >/dev/null 2>&1
	done
	/bin/rm -f /var/etc/nameserver_$1
fi
# Do not remove gateway used during filter reload.
/bin/rm -f /tmp/$1_router
/bin/rm -f /tmp/$1up
/bin/rm -f /tmp/$1_ip
/usr/local/sbin/pfSctl -c 'service reload dns'
