#!/bin/sh

/bin/rm -f /var/etc/nameserver_$1

# unset CGI environment variables so as not to confuse PHP
unset CONTENT_TYPE GATEWAY_INTERFACE REMOTE_USER REMOTE_ADDR AUTH_TYPE
unset HTTP_USER_AGENT CONTENT_LENGTH SCRIPT_FILENAME HTTP_HOST
unset SERVER_SOFTWARE HTTP_REFERER SERVER_PROTOCOL REQUEST_METHOD
unset SERVER_PORT SCRIPT_NAME SERVER_NAME

# write nameservers to file
if [ "$6" = "dns1" ]
	echo $7 > /var/etc/nameserver_$1
	/sbin/route add $7 -iface $1
fi

if [ "$8" = "dns2" ]
	echo $9 >> /var/etc/nameserver_$1
	/sbin/route add $9 -iface $1
fi

# let the configuration system know that the ip has changed.
/bin/echo $1 > /tmp/rc.newwanip
/bin/echo $4 > /tmp/$1_router
/usr/bin/touch /tmp/$1up
