#!/bin/sh

# record logout
/usr/bin/logger -p local3.info "logout,$1,$4,$5"
/sbin/pfctl -b 0.0.0.0/32 -b $4/32
/sbin/pfctl -k $4/32
/sbin/pfctl -k 0.0.0.0/32 $4/32
/sbin/pfctl -K $4/32
/sbin/pfctl -K 0.0.0.0/32 -K $4/32
