#! /usr/local/bin/php -f
<?php
/*
	sshd - Modified to work on disk based system
	Copyright 2004 Scott K Ullrich

	Original Copyright (C) 2004 Fred Mol <fredmol@xs4all.nl>.
	All rights reserved.

	Redistribution and use in source and binary forms, with or without
	modification, are permitted provided that the following conditions are met:

	1. Redistributions of source code must retain the above copyright notice,
	   this list of conditions and the following disclaimer.

	2. Redistributions in binary form must reproduce the above copyright
	   notice, this list of conditions and the following disclaimer in the
	   documentation and/or other materials provided with the distribution.

	THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
	INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
	AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
	AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
	OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
	SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
	INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
	CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
	ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
	POSSIBILITY OF SUCH DAMAGE.
*/
	require_once("config.inc");

	if(isset($config['system']['enablesshd'])) {
		/* do nothing, we're enabled */
	} else {
		if($g['booting'])
			echo "SSHD is disabled.";
		exit;
	}
	
	function file_size($file) {
	  $size = filesize($file);
	  return $size;
	}

	/*    if any of these files are 0 bytes then they are corrupted.
	 *    remove them
	 */
	$files_to_check = array('ssh_host_dsa_key','ssh_host_dsa_key.pub','ssh_host_key','ssh_host_key.pub','ssh_host_rsa_key','ssh_host_rsa_key.pub','/root/.authorized_keys');
	foreach($files_to_check as $f2c) {
		if(file_exists("/etc/ssh/{$f2c}"))
			if(file_size("/etc/ssh/{$f2c}")==0) {
				mwexec("rm /etc/ssh/ssh_host*");
			}
	}

	if (!is_dir("/var/empty")) {
		/* make ssh home directory */
		mkdir("/var/empty", 0555);
	}

	if(!file_exists("")) {
		/* Login related files. */
		touch("/var/log/lastlog");
	}

	/* Make the root passwords are the same as the web admin password. */
	conf_mount_rw();
	$fd = popen("/usr/sbin/pw usermod -n root -H 0", "w");
	fwrite($fd, $config['system']['password']);
	pclose($fd);

	/* Make the admin passwords are the same as the web admin password. */
	$fd = popen("/usr/sbin/pw usermod -n admin -H 0", "w");
	fwrite($fd, $config['system']['password']);
	pclose($fd);

	$sshConfigDir = "/etc/ssh";

	/* mop up from a badly implemented ssh keys -> cf backup */
	if($config['ssh']['dsa_key'] <> "") {
		unset($config['ssh']['dsa_key']);
		unset($config['ssh']['rsa_key']);
		unset($config['ssh']['rsa1_key']);
		unset($config['ssh']['dsa']);
		unset($config['ssh']['rsa']);
		unset($config['ssh']['rsa1']);
		unset($config['ssh']['ak']);
		write_config("Clearing SSH keys from config.xml");
	}
	
	/* are we already running?  if so exit */
	if(file_exists("/tmp/keys_generating"))
		exit;
	
	if (!file_exists("$sshConfigDir/ssh_host_key") or file_exists("/etc/keys_generating")) {
		/* remove previous keys and regen later */
		conf_mount_rw();
		mwexec("rm /etc/ssh/ssh_host_*");
		touch("/etc/keys_generating");
		touch("/tmp/keys_generating");
		echo " Generating Keys:\n";
		system("/usr/bin/nice -n20 /usr/bin/ssh-keygen -t rsa1 -N '' -f $sshConfigDir/ssh_host_key");
		system("/usr/bin/nice -n20 /usr/bin/ssh-keygen -t rsa -N '' -f $sshConfigDir/ssh_host_rsa_key");
		system("/usr/bin/nice -n20 /usr/bin/ssh-keygen -t dsa -N '' -f $sshConfigDir/ssh_host_dsa_key");
		unlink("/etc/keys_generating");
		unlink("/tmp/keys_generating");
		echo "Starting SSH... ";
	}

	$status = mwexec("/usr/sbin/sshd");
	if($status <> 0) {
		file_notice("sshd_startup", "SSHD failed to start.", "SSHD Daemon", "");
		echo "error!\n";
	} else {
		echo "done.\n";
	}
	
	conf_mount_ro();
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	exit;

	/* exit early, this needs more testing. */

	if (!file_exists("$sshConfigDir/ssh_host_key") and $config['ssh']['dsa'] == "") {
		/* generate keys */
		system("/usr/bin/nice -n20 /usr/bin/ssh-keygen -t rsa1 -N '' -f $sshConfigDir/ssh_host_key");
		system("/usr/bin/nice -n20 /usr/bin/ssh-keygen -t rsa -N '' -f $sshConfigDir/ssh_host_rsa_key");
		system("/usr/bin/nice -n20 /usr/bin/ssh-keygen -t dsa -N '' -f $sshConfigDir/ssh_host_dsa_key");

		/* save keys */
		$dsa  = file_get_contents("{$sshConfigDir}/ssh_host_dsa_key");
		$rsa  = file_get_contents("{$sshConfigDir}/ssh_host_rsa_key");
		$rsa1 = file_get_contents("{$sshConfigDir}/ssh_host_key");
		$config['ssh']['dsa'] = base64_encode($dsa);
		$config['ssh']['rsa'] = base64_encode($rsa);
		$config['ssh']['rsa1']= base64_encode($rsa1);

		/* save public keys */
		$dsapub  = file_get_contents("{$sshConfigDir}/ssh_host_dsa_key.pub");
		$rsapub  = file_get_contents("{$sshConfigDir}/ssh_host_rsa_key.pub");
		$rsa1pub = file_get_contents("{$sshConfigDir}/ssh_host_key.pub");
		$config['ssh']['dsa_key'] = base64_encode($dsapub);
		$config['ssh']['rsa_key'] = base64_encode($rsapub);
		$config['ssh']['rsa1_key']= base64_encode($rsa1pub);
		write_config("Saved SSH keys.");
	} else {
		/* restore keys */
		$rsa1 = base64_decode($config['ssh']['rsa1']);
		$rsa  = base64_decode($config['ssh']['rsa']);
		$dsa  = base64_decode($config['ssh']['dsa']);
		file_put_contents("{$sshConfigDir}/ssh_host_key", $rsa1);
		file_put_contents("{$sshConfigDir}/ssh_host_rsa_key", $rsa);
		file_put_contents("{$sshConfigDir}/ssh_host_dsa_key", $dsa);

		/* restore public keys */
		$rsa1_pub = base64_decode($config['ssh']['rsa1_key']);
		$rsa_pub  = base64_decode($config['ssh']['rsa_key']);
		$dsa_pub  = base64_decode($config['ssh']['dsa_key']);
		file_put_contents("{$sshConfigDir}/ssh_host_key.pub", $rsa1_pub);
		file_put_contents("{$sshConfigDir}/ssh_host_rsa_key.pub", $rsa_pub);
		file_put_contents("{$sshConfigDir}/ssh_host_dsa_key.pub", $dsa_pub);

		/* change keys owner to root */
		chown("{$sshConfigDir}/ssh_host_key", "root");
		chown("{$sshConfigDir}/ssh_host_rsa_key", "root");
		chown("{$sshConfigDir}/ssh_host_dsa_key", "root");

		/* change public keys owner to root */
		chown("{$sshConfigDir}/ssh_host_key.pub", "root");
		chown("{$sshConfigDir}/ssh_host_rsa_key.pub", "root");
		chown("{$sshConfigDir}/ssh_host_dsa_key.pub", "root");

		/* change mode on keys to u+rw */
		chmod("{$sshConfigDir}/ssh_host_key",0600);
		chmod("{$sshConfigDir}/ssh_host_rsa_key",0600);
		chmod("{$sshConfigDir}/ssh_host_dsa_key",0600);

		/* change mode on public keys to u+rw */
		chmod("{$sshConfigDir}/ssh_host_key.pub",0600);
		chmod("{$sshConfigDir}/ssh_host_rsa_key.pub",0600);
		chmod("{$sshConfigDir}/ssh_host_dsa_key.pub",0600);
	}

	if($config['ssh']['ak'] <> "") {
		$ak  = base64_decode($config['ssh']['ak']);
		file_put_contents("/root/.authorized_keys", $ak);
		chmod("/root/.authorized_keys",0600);
	}

	/* start sshd */
	system("/usr/sbin/sshd");
	echo "done.\n";

?>
