# $FreeBSD: src/usr.sbin/pc-sysinstall/conf/Makefile,v 1.2 2010/06/24 22:29:36 imp Exp $

NO_OBJ=

FILESGROUPS=	CONF LICENSE
CONF=		exclude-from-upgrade pc-sysinstall.conf avail-langs
CONFDIR=	${SHAREDIR}/pc-sysinstall/conf
LICENSE=	licenses/bsd-en.txt licenses/intel-en.txt licenses/nvidia-en.txt
LICENSEDIR=	${SHAREDIR}/pc-sysinstall/conf/license

.include <bsd.prog.mk>
