# $FreeBSD: src/usr.sbin/pc-sysinstall/doc/Makefile,v 1.1 2010/06/24 22:21:47 imp Exp $

FILES=	help-disk-list help-disk-size help-index help-start-autoinstall

FILESDIR=${SHAREDIR}/pc-sysinstall/doc
NO_OBJ=

.include <bsd.prog.mk>
