</td></tr></table></td>
  </tr>
  <tr align="center" valign="top" bgcolor="#990000">
    <td colspan="2" class="cpline"><a target="_NEW" href="http://www.pfSense.com">pfSense</a> is &copy; 2004-2005 by Scott Ullrich. All Rights Reserved.
<br>pfSense is originally based on m0n0wall which is &copy; 2002-2004 by Manuel Kasper.
      All rights reserved.&nbsp; [<a href="/license.php" class="tblnk">view license</a>]</td>
  </tr>
</table>
</div>
<script type="text/javascript">
window.onload=function(){
if(!NiftyCheck())
    return;
Rounded("div#niftyOutter","tr bottom","#FFF","#D4DDFF","smooth");
}
</script>