<head>
    <title><?=gentitle($pgtitle);?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <link href="gui.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="niftycssCode.css">
    <link rel="stylesheet" type="text/css" href="niftycssprintCode.css" media="print">
    <script type="text/javascript" src="niftyjsCode.js"></script>
</head>